
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

PAGE_SIZE = 5
cloudinary.cloud_name=de0pt2lzw
cloudinary.api_id=269448242686499
cloudinary.api_secret=36ckrJAaSBk2wrWeU3kU9ICwTOM